name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Access a secret
      run: |
        echo "My secret value is: ${{ secrets.MY_PASSWORD }}"
      env:
        API_KEY: ${{ secrets.MY_PASSWORD }}
    - name: Run a one-line script
      run: echo Hello, GitHub Actions!
